version: "3"
services:
  client:
    build:
      context: ./client
    container_name: "moodie_client"
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
    volumes:
      - /usr/src/app/node_modules
  db:
    image: mongo:latest
    container_name: "moodie_db"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
