FROM node:10 AS builder

WORKDIR /usr/src/shared
COPY shared/package.json shared/package-lock.json ./
RUN npm install
COPY shared .
RUN npm run build

WORKDIR /usr/src/app
COPY mood/package.json mood/package-lock.json ./
RUN npm install
COPY mood .
RUN npm run build


FROM node:10-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./

CMD ["npm", "run", "start:prod"]
