version: "3"
services:
  auth:
    build:
      context: .
      dockerfile: ./Dockerfile-auth
    container_name: "moodie_auth"
    environment:
      - NODE_ENV=${AUTH_NODE_ENV}
      - PORT=${AUTH_PORT}
      - AUTH_DATABASE_HOST=${AUTH_DATABASE_HOST}
      - AUTH_ACCESS_TOKEN_EXPIRATION=${AUTH_ACCESS_TOKEN_EXPIRATION}
      - AUTH_REFRESH_TOKEN_EXPIRATION=${AUTH_REFRESH_TOKEN_EXPIRATION}

    ports:
      - 3010:${AUTH_PORT}
    depends_on:
      - db
      - notifications
    networks:
      - moodie-network

  notifications:
    build:
      context: .
      dockerfile: ./Dockerfile-notifications

    container_name: "moodie_notifications"
    volumes:
      - ./shared:/usr/src/shared
    environment:
      - NODE_ENV=${NOTIFICATIONS_NODE_ENV}
      - NOTIFICATIONS_PORT=${NOTIFICATIONS_PORT}
      - CACHE_HOST=${CACHE_HOST}
      - AUTH_PROVIDER=${AUTH_PROVIDER}
      - AUTH_VERIFICATION_ENDPOINT=${AUTH_VERIFICATION_ENDPOINT}
    ports:
      - 3015:${NOTIFICATIONS_PORT}
    depends_on:
      - cache
    networks:
      - moodie-network

  mood:
    build:
      context: .
      dockerfile: ./Dockerfile-mood
    container_name: "moodie_mood"
    volumes:
      - ./shared:/usr/src/shared
    environment:
      - NODE_ENV=${MOOD_NODE_ENV}
      - PORT=${MOOD_PORT}
      - MOOD_DATABASE_HOST=${MOOD_DATABASE_HOST}
      - AUTH_PROVIDER=${AUTH_PROVIDER}
      - AUTH_VERIFICATION_ENDPOINT=${AUTH_VERIFICATION_ENDPOINT}

    ports:
      - 3020:${MOOD_PORT}
    depends_on:
      - db
      - auth
    networks:
      - moodie-network

  db:
    image: mongo:latest
    container_name: "moodie_db"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - moodie-network

  cache:
    build:
      context: .
      dockerfile: ./Dockerfile-cache
    hostname: "cache"
    container_name: "moodie_cache"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - moodie-network

networks:
  moodie-network:
