version: "3"
services:
  # client:
  #   build:
  #     context: ./client
  #   container_name: "moodie_client"
  #   environment:
  #     - PORT=3000
  #     - NODE_ENV=production
  #   ports:
  #     - 3000:3000
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   volumes:
  #     - /usr/src/app/node_modules
  auth:
    build:
      context: ./auth
    container_name: "moodie_auth"
    environment:
      - NODE_ENV=${AUTH_NODE_ENV}
      - PORT=${AUTH_PORT}
      - AUTH_DATABASE_HOST=${AUTH_DATABASE_HOST}
      - AUTH_ACCESS_TOKEN_EXPIRATION=${AUTH_ACCESS_TOKEN_EXPIRATION}
      - AUTH_REFRESH_TOKEN_EXPIRATION=${AUTH_REFRESH_TOKEN_EXPIRATION}

    ports:
      - 3010:${AUTH_PORT}
    depends_on:
      - db
    networks:
      - moodie-network

  mood:
    build:
      context: ./mood
    container_name: "moodie_mood"
    environment:
      - NODE_ENV=${MOOD_NODE_ENV}
      - PORT=${MOOD_PORT}
      - MOOD_DATABASE_HOST=${MOOD_DATABASE_HOST}
      - MOOD_AUTH_PROVIDER=${MOOD_AUTH_PROVIDER}
      - MOOD_AUTH_VERIFICATION_ENDPOINT=${MOOD_AUTH_VERIFICATION_ENDPOINT}

    ports:
      - 3020:${MOOD_PORT}
    depends_on:
      - db
      - auth
    networks:
      - moodie-network

  db:
    image: mongo:latest
    container_name: "moodie_db"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - moodie-network

networks:
  moodie-network:
